name: ringoflutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.1
  material_color_utilities: ^0.5.0
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  flutter_image: ^4.1.6
  google_maps_flutter: ^2.3.1
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2
  qr_flutter: ^4.1.0
  geolocator: ^9.0.2
  pull_down_button: ^0.9.3
  google_sign_in: ^6.1.4
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.2.0
  flutter_slidable: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.12
  sign_in_with_apple: ^5.0.0
  status_alert: ^1.0.1
  flutter_rating_bar: ^4.0.1
  page_view_dot_indicator: ^2.3.0
  multi_select_flutter: ^4.1.3
  add_2_calendar: ^2.2.4
  share_plus: ^7.1.0
  social_share: ^2.3.1
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.1
  image: ^4.1.3
  screenshot: ^2.1.0
  adaptive_action_sheet: ^2.0.2
  flutter_stripe: ^9.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"

flutter:
  assets:
    - assets/images/
    - assets/map/dark.txt
    - assets/map/dark.json
    - assets/map/light.txt
    - assets/map/light.json

  uses-material-design: false